config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  resources :blogs
  root 'static_pages#index'
  get 'static_pages/about'
  get 'static_pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :admin
  validate :content, :title
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end
  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(title: params[:blog][:title], content: params[:content][:info])
    @blog.admin_id = current_admin.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.permit(:content, :title)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= cktext_area :content, :info, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="main">
  <p id="notice"><%= notice %></p>
  <div class="add-blog">
    <% if admin_signed_in? %>
      <a class="btn-floating btn-large waves-effect waves-light red" href="blogs/new"><i class="material-icons">add</i></a>
      <a class="btn-floating btn-large waves-effect waves-light red" href="/admins/sign_out" data-method="delete"><i class="material-icons">exit_to_app</i></a>
    <% else %>
      <a class="btn-floating btn-large waves-effect waves-light red" href="/admins/sign_in"><i class="material-icons">person</i></a>
    <% end %>
  </div>
  <div class="row">
    <% if @blogs.any? %>
      <% @blogs.each do |blog| %>
         <div class="col s12 m3">
           <div class="card">
             <div class="card-image">
               <%= image_tag 'bg' %>
               <span class="card-title"><%= blog.title %></span>
             </div>
             <div class="card-content">
               <p><%= blog.content.first(150).html_safe %></p>
             </div>
             <div class="card-action">
               <%= link_to 'Read More', blog_path(blog) %>
             </div>
           </div>
         </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/blogs/new.html.erb
<div class="main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>

</div>
<script>
  = javascript_include_tag Ckeditor.cdn_url
</script>

app/views/blogs/show.html.erb
<div class="main">
  <p id="notice"><%= notice %></p>
  <div class="title">
    <h5><%= @blog.title %></h5>
  </div>
  <div class="content">
    <%= @blog.content.html_safe %>
  </div>
<% if admin_signed_in? %>
  <a class="btn-floating btn-large waves-effect waves-light red" href="/blogs/<%= @blog.id %>/edit"><i class="material-icons">create</i></a>
<% end %>
<a class="btn-floating btn-large waves-effect waves-light red" href="/blogs"><i class="material-icons">keyboard_backspace</i></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YOMEF</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="tranparent">
       <div class="nav-wrapper">
         <a href="/" class="brand-logo">YOMEF</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
           <li><%= link_to 'About', static_pages_about_path, style: 'color: white' %></li>
           <li><%= link_to 'Testimonials', blogs_path, style: 'color: white' %></li>
         </ul>
       </div>
     </nav>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer class="page-footer blue">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Susan N. Waititu</h5>
                <p class="grey-text text-lighten-4">Director</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Contact</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Cell: 0712 382 202</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Office: 0723 827 686</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Email: yomef2015@outlook.com</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Copyright YOMEF
            <a class="grey-text text-lighten-4 right" href="https://kiburei.github.io" target="_blank">Kiburei</a>
            </div>
          </div>
        </footer>

</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<div class="header">
  <div class="banner row">
    <div class="logo col s6">
      <%= image_tag 'yomeflogobig.png', height: 250 %>
    </div>
    <div class="brand-name col s6">
      <h4 class="white-text">YOUNGMOMS EMPOWERMENT FOUNDATION GROUP <span class="logo-text">(YOMEF)</span></h4>
    </div>
  </div>
  <div class="action">
    <a class="waves-effect waves-light btn-large modal-trigger red" href="#modal1"><span class="white-text">Donate</span></a>

    <!-- Modal Structure -->
    <div id="modal1" class="modal">
      <div class="modal-content">
        <p>ACC NO:</p>
        <p>YOUNGMOMS EMPOWERMENT FOUNDATION GROUP</p>
        <p>CO-OPERATIVE BANK JUJA BRANCH</p>
        <p>01134581825300</p>
      </div>
      <div class="modal-footer">
        <div class="modal-mark">
          <%= image_tag 'yomeflogo', height: 40 %>
        </div>
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Standing a Second Chance</a>
      </div>
    </div>
  </div>

</div>
<div class="main">
  <div class="intro">
    <h3>About Us</h3>
    <p>YOMEF is a non-profit organisation that rescues teenage mothers from vulnerable homes and OVC. It is located in Juja Sub-County in Kiambu County.</p>
  </div>
    <div class="row">
      <div class="col s12 m6">
        <div class="card-panel blue">
          <h5 class="white-text">Vision</h5>
          <span class="white-text">Our vision is to empower young mothers by reducing
             stigma and marginalization attached to teenage parenthood within our
             community. We intend to educate them on their sexual and reproductive
             health so as to curb the early pregnacies and risks associated with
             the vice. We also encourage them to resume schooling after offering
             sufficient counseling and constantly remind them about the dangers
             involved in teenage parenting
          </span>
        </div>
      </div>
      <div class="col s12 m6">
        <div class="card-panel blue">
          <h5 class="white-text">Mission</h5>
          <span class="white-text">Our mission is to mitigate the impact of HIV/AIDS
            and abortion at the grassroot level through community empowerment. The
            group offers provision of counseling the young mothers, enlightenign
            them on nutrition, psychological support and protection, micro-finance
            education, voluntary savings and loan trainings as we stipulate the
            vitality of education to empower them. We also inend to endow them
            with basic skills in artwork like bead-work, tie and dye and weaving.
          </span>
        </div>
      </div>
    </div>
    <div class="justification">
      <h4>Our Objectives</h4>
      <p>The main objective is to break the cycle of young mithers getting more
         children while in the process of trying to fend for their young ones,
         putting themselves in the position to of more unwanted pregnancies,
         abortions, health risks and even early marriages of convinience. This
         girls need help and their voices echoed so as to get back on their feet by:
         <ol>
           <li>Proper counseling and arming them the life skills will help them rise over their delicate situations</li>
           <li>Empowering their guardians financially will enable them to fend for their babies as they resume schooling</li>
           <li>Empower with practical skills those who may be unable to resume normal schooling.</li>
           <li>Offer entreprenurial skills and training to enable them to sustain themselves in the long run.</li>
         </ol>
       </p>
    </div>
    <div class="project-area">
      <h4>Project Area</h4>
      <p>The project area is in Juja whereby we have targeted ten girls from every
        ward namely Witeithie, Theta, Kalimoni, Juja and Murera. The questionnaire
        and the sampling is done on girls aged 18 years and below who have children
        and are from vulnerable families. The data collection is done by the social
        workers representing every ward which they are well conversant with.
      </p>
    </div>

</div>
<script>
  $(document).ready(function(){
   $('#modal1').modal();
  });
</script>